USE G2_PROYECTO_G4_TERREMOTOS;
GO

DROP TABLE IF EXISTS dbo.Location;
GO
DROP TABLE IF EXISTS dbo.Earthquake;
GO 

CREATE TABLE Earthquake (
    ID INT PRIMARY KEY,
    DATE DATE NOT NULL,
    TIME TIME NOT NULL,
    DEPTH FLOAT NOT NULL,
    MAGNITUDE FLOAT NOT NULL
);


CREATE TABLE Location (
    ID INT PRIMARY KEY,
    PLACE TEXT  NOT NULL,
    COUNTRY VARCHAR(255) NOT NULL,
    LATITUDE DECIMAL(10, 8) NOT NULL,
    LONGITUDE DECIMAL(10, 8) NOT NULL,
     FOREIGN KEY (ID) REFERENCES Earthquake(ID)
);
