USE G2_PROYECTO_G4_TERREMOTOS
GO

DROP TABLE IF EXISTS dbo.Location;
GO
DROP TABLE IF EXISTS dbo.Earthquake;
GO 

CREATE TABLE dbo.Earthquake (
    ID VARCHAR(255) PRIMARY KEY,
    DATE DATE NOT NULL,
    TIME TIME NOT NULL,
    DEPTH FLOAT NOT NULL,
    MAGNITUDE FLOAT
);


CREATE TABLE dbo.Location (
    ID VARCHAR(255) PRIMARY KEY,
    PLACE TEXT,
    COUNTRY VARCHAR(255),
    LATITUDE VARCHAR(255) NOT NULL,
    LONGITUDE VARCHAR(255) NOT NULL,
    -- FOREIGN KEY (ID) REFERENCES Earthquake(ID)
);
