USE G2_PROYECTO_G4_VOLCANES;
GO

DROP TABLE IF EXISTS dbo.Location;
GO
DROP TABLE IF EXISTS dbo.Volcano;
GO 

CREATE TABLE Volcano (
    VOLCANONAME VARCHAR(50) PRIMARY KEY,
    ELEVATION INT NOT NULL,
    TYPE VARCHAR(255)NOT NULL,
    STATUS VARCHAR(255) NOT NULL,
    VOLCANOEXPLOSIVITY INT NOT NULL,
    DEATH INT
);

CREATE TABLE Location (
    VOLCANONAME VARCHAR(50) PRIMARY KEY,
    PLACE TEXT NOT NULL,
    COUNTRY VARCHAR(255) NOT NULL,
    LATITUDE DECIMAL(10, 8) NOT NULL,
    LONGITUDE DECIMAL(10, 8) NOT NULL,
    FOREIGN KEY (VOLCANONAME) REFERENCES Volcano(VOLCANONAME)
);